import {
  SubstrateNode,
  CapabilityDefinition,
  CAPPOGrant,
  PluginModule,
  AgentTask,
  PGLRecord,
  MCPTool,
  FPIProvider,
  FPIResourceAllocation,
  FPIExecutionJob,
  FPIBillingSettlement,
} from './types';

export const INITIAL_SUBSTRATE_NODES: SubstrateNode[] = [
  {
    id: 'node-local-k8s',
    name: 'Local Container Enclave',
    type: 'local_k8s',
    region: 'Local / On-Prem',
    localityBoundary: 'Secure Enclave Alpha (Local Sovereign Boundary)',
    status: 'online',
    latencyMs: 3,
    cpuUsagePct: 24,
    memoryUsagePct: 41,
    activeWorkloads: 12,
    isSovereign: true,
    mcpEnabled: true,
    supportedCapabilities: ['cap-compute-v1', 'cap-db-persist', 'cap-agent-recurse', 'cap-mcp-toolcall'],
  },
  {
    id: 'node-aws-edge',
    name: 'AWS Edge Node (US-East)',
    type: 'aws_edge',
    region: 'us-east-1',
    localityBoundary: 'AWS Local Zone / Outposts',
    status: 'online',
    latencyMs: 28,
    cpuUsagePct: 58,
    memoryUsagePct: 62,
    activeWorkloads: 48,
    isSovereign: false,
    mcpEnabled: true,
    supportedCapabilities: ['cap-compute-v1', 'cap-db-persist', 'cap-mcp-toolcall'],
  },
  {
    id: 'node-azure-sovereign',
    name: 'Azure Sovereign Cloud',
    type: 'azure_sovereign',
    region: 'eu-west-1 (Sovereign)',
    localityBoundary: 'National Data Center Isolation',
    status: 'online',
    latencyMs: 45,
    cpuUsagePct: 32,
    memoryUsagePct: 49,
    activeWorkloads: 19,
    isSovereign: true,
    mcpEnabled: true,
    supportedCapabilities: ['cap-compute-v1', 'cap-db-persist', 'cap-agent-recurse'],
  },
  {
    id: 'node-rf-edge',
    name: 'RF Microcontroller Gateway',
    type: 'rf_microcontroller',
    region: 'Edge RF Boundary',
    localityBoundary: 'RF-Powered Embedded Enclave',
    status: 'online',
    latencyMs: 12,
    cpuUsagePct: 78,
    memoryUsagePct: 84,
    activeWorkloads: 4,
    isSovereign: true,
    mcpEnabled: false,
    supportedCapabilities: ['cap-rf-telemetry', 'cap-compute-v1'],
  },
];

export const CAPABILITY_CATALOG: CapabilityDefinition[] = [
  {
    id: 'cap-compute-v1',
    name: 'Substrate.Compute.Execute',
    description: 'Execute portable stateless workload across local container or remote cloud substrate',
    category: 'compute',
    requiredRole: 'operator:compute',
    schemaJson: JSON.stringify({ action: 'string', parameters: 'object', timeoutMs: 'number' }, null, 2),
  },
  {
    id: 'cap-db-persist',
    name: 'Substrate.Data.PersistRecord',
    description: 'Append immutable persistence payload into locality-bounded data store',
    category: 'data_persistence',
    requiredRole: 'storage:writer',
    schemaJson: JSON.stringify({ collection: 'string', document: 'object', encrypted: 'boolean' }, null, 2),
  },
  {
    id: 'cap-agent-recurse',
    name: 'Substrate.Herdr.AgentLoop',
    description: 'Trigger autonomous agent self-evaluation, code refactoring, or sub-agent dispatch',
    category: 'agent_recursion',
    requiredRole: 'agent:herdr_operator',
    schemaJson: JSON.stringify({ prompt: 'string', recursionDepth: 'number', targetMetric: 'string' }, null, 2),
  },
  {
    id: 'cap-rf-telemetry',
    name: 'Substrate.Hardware.RFTelemetry',
    description: 'Read or stream RF-powered microcontroller sensor frames in zero-latency local loop',
    category: 'edge_rf',
    requiredRole: 'device:rf_telemetry',
    schemaJson: JSON.stringify({ frequencyMhz: 'number', packetSize: 'number' }, null, 2),
  },
  {
    id: 'cap-mcp-toolcall',
    name: 'Substrate.MCP.InvokeTool',
    description: 'Model Context Protocol tool execution across microservice mesh',
    category: 'mcp_bridge',
    requiredRole: 'mcp:invoker',
    schemaJson: JSON.stringify({ method: 'string', params: 'object' }, null, 2),
  },
];

export const INITIAL_CAPPO_GRANTS: CAPPOGrant[] = [
  {
    grantId: 'cappo-grant-alpha-001',
    subject: 'agent:herdr-autonomous-core',
    allowedCapabilities: ['cap-compute-v1', 'cap-db-persist', 'cap-agent-recurse', 'cap-mcp-toolcall'],
    expiresAt: Date.now() + 86400000 * 30, // 30 days
    signature: 'sig_cappo_9a8b7c6d5e4f3a2b1c0d',
    isRevoked: false,
  },
  {
    grantId: 'cappo-grant-restricted-002',
    subject: 'external:read-only-guest',
    allowedCapabilities: ['cap-compute-v1'],
    expiresAt: Date.now() + 86400000 * 7,
    signature: 'sig_cappo_112233445566778899',
    isRevoked: false,
  },
];

export const INITIAL_PLUGINS: PluginModule[] = [
  {
    id: 'plugin-aws-bridge',
    name: 'AWS Portable Cloud Bridge',
    category: 'Cloud Adapter',
    version: '1.4.2',
    enabled: true,
    description: 'Enables seamless AWS EC2/Lambda fallback execution when local substrate yields 503.',
    author: 'Veklom Substrate WG',
    downloads: 14200,
    activeCapabilityId: 'cap-compute-v1',
  },
  {
    id: 'plugin-azure-sovereign',
    name: 'Azure Sovereign Enclave',
    category: 'Cloud Adapter',
    version: '2.0.1',
    enabled: true,
    description: 'Connects EU/US national data center sovereign instances with hardware attestation.',
    author: 'Computless Security',
    downloads: 9800,
    activeCapabilityId: 'cap-db-persist',
  },
  {
    id: 'plugin-mcp-connector',
    name: 'MCP Universal Protocol Proxy',
    category: 'Protocol Extension',
    version: '0.9.5',
    enabled: true,
    description: 'Translates standard Model Context Protocol JSON-RPC into CAPPO-governed substrate actions.',
    author: 'Anthropic/Veklom Open Spec',
    downloads: 28400,
    activeCapabilityId: 'cap-mcp-toolcall',
  },
  {
    id: 'plugin-pgl-verifier',
    name: 'PGL Proof Graph Auditing Engine',
    category: 'Security / Audit',
    version: '3.1.0',
    enabled: true,
    description: 'Generates real-time SHA-256 state transition hashes for evidence preservation.',
    author: 'Core Substrate Labs',
    downloads: 31000,
    activeCapabilityId: 'cap-db-persist',
  },
  {
    id: 'plugin-x402-settlement',
    name: 'x402 Micropayment & Gas Metering',
    category: 'Security / Audit',
    version: '1.2.0',
    enabled: true,
    description: 'Handles HTTP 402 gas metering for micro-transactions across federated compute nodes.',
    author: 'PaySubstrate Tech',
    downloads: 18900,
    activeCapabilityId: 'cap-compute-v1',
  },
  {
    id: 'plugin-rf-sensor',
    name: 'RF Microcontroller Driver',
    category: 'Hardware Connector',
    version: '0.4.1',
    enabled: false,
    description: 'Interfaces with ultra-low power ambient RF microcontrollers on factory floor.',
    author: 'EdgeRF Corp',
    downloads: 4200,
    activeCapabilityId: 'cap-rf-telemetry',
  },
];

export const INITIAL_AGENT_TASKS: AgentTask[] = [
  {
    id: 'herdr-task-01',
    name: 'Substrate Workload Auto-Balancer',
    status: 'RECURSING',
    capabilitiesUsed: ['cap-compute-v1', 'cap-agent-recurse'],
    recursionDepth: 4,
    maxRecursionDepth: 10,
    lastOptimizedAt: new Date(Date.now() - 120000).toISOString(),
    logs: [
      '[Herdr-Core] Agent self-inspection initiated.',
      '[HRMR] Evaluated latency: Local (3ms) vs AWS (28ms). Preferred path set to Local Container.',
      '[CAPPO] Authority grant cappo-grant-alpha-001 verified. Token signature valid.',
      '[Recursion] Optimized internal state dispatch loop. Ops increased by +18.4%.',
    ],
    metrics: {
      opsPerSec: 142.5,
      tasksDriven: 890,
      successRatePct: 99.8,
    },
  },
  {
    id: 'herdr-task-02',
    name: 'PGL Cryptographic Evidence Verifier',
    status: 'EVALUATING',
    capabilitiesUsed: ['cap-db-persist', 'cap-mcp-toolcall'],
    recursionDepth: 2,
    maxRecursionDepth: 5,
    lastOptimizedAt: new Date(Date.now() - 450000).toISOString(),
    logs: [
      '[PGL Engine] Auditing last 50 state transitions.',
      '[Evidence] Proof hash tree merkle root verified across 4 nodes.',
      '[x402] Gas settlement batch processed: 0.0042 VEK settled.',
    ],
    metrics: {
      opsPerSec: 64.2,
      tasksDriven: 412,
      successRatePct: 100,
    },
  },
];

export const INITIAL_PGL_RECORDS: PGLRecord[] = [
  {
    id: 'pgl-rec-1001',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    transactionId: 'tx-vk-88192031',
    capabilityId: 'cap-compute-v1',
    cappoGrantId: 'cappo-grant-alpha-001',
    executedNodeId: 'node-local-k8s',
    requestPayloadHash: '0x8f3c9e1a2b4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f',
    responseHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    pglSignature: 'pgl_sig_secp256k1_7a8b9c0d1e2f3a4b',
    x402GasSettled: 0.0012,
    verifiable: true,
  },
  {
    id: 'pgl-rec-1002',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    transactionId: 'tx-vk-88192032',
    capabilityId: 'cap-db-persist',
    cappoGrantId: 'cappo-grant-alpha-001',
    executedNodeId: 'node-aws-edge',
    requestPayloadHash: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
    responseHash: '0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
    pglSignature: 'pgl_sig_secp256k1_9c0d1e2f3a4b5c6d',
    x402GasSettled: 0.0028,
    verifiable: true,
  },
];

export const INITIAL_FPI_PROVIDERS: FPIProvider[] = [
  {
    id: 'fpi-provider-aws-sovereign',
    providerName: 'AWS Nitro Enclave Provider',
    providerType: 'hyperscaler',
    endpointUrl: 'https://fpi.aws.veklom-substrate.net/v1',
    authKeyHash: '0xfpi_key_aws_88a91c02',
    regions: ['us-east-1', 'eu-central-1', 'ap-southeast-1'],
    status: 'active',
    slaUptimePct: 99.99,
    maxLatencyMs: 18,
    isSovereignEnclave: true,
    supportedCapabilities: ['cap-compute-v1', 'cap-db-persist', 'cap-mcp-toolcall'],
    pricing: { pricePerComputeUnitVEK: 0.0008, spotDiscountPct: 35, currency: 'VEK' },
    quota: { totalAllocatedUnits: 1200, usedUnits: 480, maxCapacityUnits: 5000 },
    registeredAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    lastHeartbeatAt: new Date().toISOString(),
  },
  {
    id: 'fpi-provider-equinix-edge',
    providerName: 'Equinix Metal Baremetal Edge',
    providerType: 'edge_telecom',
    endpointUrl: 'https://fpi.equinix.computless.org/v1',
    authKeyHash: '0xfpi_key_eqx_77b31d04',
    regions: ['us-west-2', 'eu-west-1'],
    status: 'active',
    slaUptimePct: 99.95,
    maxLatencyMs: 8,
    isSovereignEnclave: false,
    supportedCapabilities: ['cap-compute-v1', 'cap-rf-telemetry', 'cap-mcp-toolcall'],
    pricing: { pricePerComputeUnitVEK: 0.0005, spotDiscountPct: 20, currency: 'VEK' },
    quota: { totalAllocatedUnits: 800, usedUnits: 320, maxCapacityUnits: 2500 },
    registeredAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    lastHeartbeatAt: new Date().toISOString(),
  },
  {
    id: 'fpi-provider-gcp-confidential',
    providerName: 'Google Cloud Confidential Space',
    providerType: 'sovereign_enclave',
    endpointUrl: 'https://fpi.gcp.sovereign-cloud.io/v1',
    authKeyHash: '0xfpi_key_gcp_99c42e05',
    regions: ['europe-west3', 'us-central1'],
    status: 'active',
    slaUptimePct: 99.999,
    maxLatencyMs: 22,
    isSovereignEnclave: true,
    supportedCapabilities: ['cap-compute-v1', 'cap-db-persist', 'cap-agent-recurse'],
    pricing: { pricePerComputeUnitVEK: 0.0012, spotDiscountPct: 40, currency: 'VEK' },
    quota: { totalAllocatedUnits: 2000, usedUnits: 850, maxCapacityUnits: 10000 },
    registeredAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    lastHeartbeatAt: new Date().toISOString(),
  },
  {
    id: 'fpi-provider-decentralized-gpu',
    providerName: 'Akash Decentralized GPU Swarm',
    providerType: 'decentralized_mesh',
    endpointUrl: 'https://fpi-mesh.akash-substrate.net/v1',
    authKeyHash: '0xfpi_key_akash_33d12f09',
    regions: ['global-mesh-p2p'],
    status: 'degraded',
    slaUptimePct: 98.5,
    maxLatencyMs: 65,
    isSovereignEnclave: false,
    supportedCapabilities: ['cap-compute-v1', 'cap-agent-recurse'],
    pricing: { pricePerComputeUnitVEK: 0.0003, spotDiscountPct: 50, currency: 'VEK' },
    quota: { totalAllocatedUnits: 500, usedUnits: 410, maxCapacityUnits: 1500 },
    registeredAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 420000).toISOString(),
  },
];

export const INITIAL_FPI_ALLOCATIONS: FPIResourceAllocation[] = [
  {
    id: 'fpi-alloc-001',
    providerId: 'fpi-provider-aws-sovereign',
    providerName: 'AWS Nitro Enclave Provider',
    granteeSubject: 'agent:herdr-autonomous-core',
    computeUnits: 120,
    memoryGb: 256,
    gpuCores: 8,
    allocationType: 'reserved',
    status: 'active',
    leaseDurationMinutes: 1440, // 24 hours
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    expiresAt: new Date(Date.now() + 79200000).toISOString(),
    x402TotalLeaseCostVEK: 0.096,
  },
  {
    id: 'fpi-alloc-002',
    providerId: 'fpi-provider-gcp-confidential',
    providerName: 'Google Cloud Confidential Space',
    granteeSubject: 'tenant:finance-audit-enclave',
    computeUnits: 300,
    memoryGb: 512,
    gpuCores: 16,
    allocationType: 'spot',
    status: 'active',
    leaseDurationMinutes: 720,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    expiresAt: new Date(Date.now() + 28800000).toISOString(),
    x402TotalLeaseCostVEK: 0.216,
  },
];

export const INITIAL_FPI_JOBS: FPIExecutionJob[] = [
  {
    id: 'fpi-job-8801',
    providerId: 'fpi-provider-aws-sovereign',
    providerName: 'AWS Nitro Enclave Provider',
    capabilityId: 'cap-compute-v1',
    cappoGrantId: 'cappo-grant-alpha-001',
    status: 'completed',
    executionTimeMs: 14,
    x402GasSettled: 0.0012,
    pglProofSignature: 'pgl_fpi_sig_0x99a81b2c3d4e5f6a',
    submittedAt: new Date(Date.now() - 1200000).toISOString(),
    completedAt: new Date(Date.now() - 1198500).toISOString(),
    outputSummary: 'Stateless execution completed inside Nitro Enclave with hardware attestation.',
    logs: [
      '[FPI Proxy] Authorized CAPPO grant cappo-grant-alpha-001.',
      '[FPI Gateway] Payload routed to AWS Nitro Enclave (us-east-1).',
      '[FPI Execution] Workload finished in 14ms.',
      '[x402 Settlement] Metered 0.0012 VEK. PGL proof signed.',
    ],
  },
  {
    id: 'fpi-job-8802',
    providerId: 'fpi-provider-gcp-confidential',
    providerName: 'Google Cloud Confidential Space',
    capabilityId: 'cap-db-persist',
    cappoGrantId: 'cappo-grant-alpha-001',
    status: 'completed',
    executionTimeMs: 22,
    x402GasSettled: 0.0018,
    pglProofSignature: 'pgl_fpi_sig_0x77c82d3e4f5a6b7c',
    submittedAt: new Date(Date.now() - 600000).toISOString(),
    completedAt: new Date(Date.now() - 598000).toISOString(),
    outputSummary: 'Sovereign data persisted to GCP Confidential Storage with PGL proof ledger seal.',
    logs: [
      '[FPI Proxy] CAPPO grant verified.',
      '[FPI Discovery] HRMR matched GCP Confidential Space (europe-west3).',
      '[FPI Execution] Immutable document stored.',
      '[x402 Settlement] Metered 0.0018 VEK.',
    ],
  },
];

export const INITIAL_FPI_SETTLEMENTS: FPIBillingSettlement[] = [
  {
    id: 'fpi-stl-2026-08',
    providerId: 'fpi-provider-aws-sovereign',
    providerName: 'AWS Nitro Enclave Provider',
    period: '2026-08-01 - 2026-08-13',
    jobsExecuted: 4120,
    totalComputeUnitsUsed: 38400,
    totalx402EarnedVEK: 30.72,
    payoutStatus: 'settled',
    payoutTxHash: '0x3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'fpi-stl-2026-08-02',
    providerId: 'fpi-provider-gcp-confidential',
    providerName: 'Google Cloud Confidential Space',
    period: '2026-08-01 - 2026-08-13',
    jobsExecuted: 2890,
    totalComputeUnitsUsed: 29100,
    totalx402EarnedVEK: 34.92,
    payoutStatus: 'pending',
    payoutTxHash: '0x9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const MCP_TOOLS_CATALOG: MCPTool[] = [
  {
    name: 'substrate_execute_workload',
    description: 'Executes a stateless container workload on preferred substrate node with CAPPO authorization.',
    capabilityBinding: 'cap-compute-v1',
    inputSchema: {
      type: 'object',
      properties: {
        command: { type: 'string', description: 'Container execution payload or script' },
        timeoutMs: { type: 'number', description: 'Execution timeout limit' },
      },
      required: ['command'],
    },
  },
  {
    name: 'substrate_persist_evidence',
    description: 'Writes cryptographic record to Proof Graph Ledger and returns immutable proof hash.',
    capabilityBinding: 'cap-db-persist',
    inputSchema: {
      type: 'object',
      properties: {
        payload: { type: 'object', description: 'Data structure to hash and seal' },
        cappoGrantId: { type: 'string', description: 'CAPPO Grant authorization token' },
      },
      required: ['payload', 'cappoGrantId'],
    },
  },
  {
    name: 'herdr_trigger_agent_recursion',
    description: 'Invokes Herdr agent self-hosting loop to optimize runtime or dispatch sub-tasks.',
    capabilityBinding: 'cap-agent-recurse',
    inputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string', description: 'Target Herdr task ID' },
        recursionGoal: { type: 'string', description: 'Target optimization objective' },
      },
      required: ['taskId', 'recursionGoal'],
    },
  },
];
