allowBuilds:
  '@google/genai': set this to true or false
  '@openrouter/sdk': set this to true or false
  '@parcel/watcher': set this to true or false
  '@reown/appkit': set this to true or false
  core-js: set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false
