"use client";
import { useEffect } from "react";
import { CircleDollarSign } from "lucide-react";
import { getStage } from "@/lib/cos/stages";
import { useStageData } from "@/lib/cos/useStageData";
import { SectionShell } from "@/components/cos/SectionShell";
import { HonestEmpty, Pillar } from "@/components/cos/SectionPillars";
import { JsonPanel, PaymentChallenge } from "@/components/cos/StageParts";
export default function SettlePage(){const stage=getStage("settle"),data=useStageData("settle");const p0=stage.endpoints[0]?.path??"/.well-known/x402",p1=stage.endpoints[1]?.path??"/api/v1/pricing";useEffect(()=>{for(const e of stage.endpoints)if(e.method==="GET"&&!e.path.includes("{"))void data.call(e)},[data.call,stage.endpoints]);const discovery=data.payloads[`GET ${p0}`],pricing=data.payloads[`GET ${p1}`];const challenge=Object.values(data.payloads).find((value)=>value&&typeof value==="object"&&"x402_version" in value);return <SectionShell stage={stage} proof={data.stageProof} records={data.records}><div className="xl:col-span-2"><Pillar title="Work" proof={discovery?data.records[0]?.proof??"Needs proof":"Needs proof"} detail="Settlement binding is shown only from returned discovery and pricing documents."><div className="flex items-center gap-3"><CircleDollarSign className="text-cos-accent" size={19}/><span className="text-sm text-cos-text">M2M settlement discovery</span></div><div className="mt-4">{challenge?<PaymentChallenge value={challenge}/>:<JsonPanel value={discovery} empty={`GET ${p0} has not returned a discovery document.`}/>}</div></Pillar></div><Pillar title="Telemetry" proof={pricing?data.records[1]?.proof??"Needs proof":"Needs proof"}><JsonPanel value={pricing} empty={`GET ${p1} has not returned pricing.`}/></Pillar><Pillar title="Authority" proof="Needs proof"><HonestEmpty title="No settlement authority returned" route="GET /api/v1/pricing" detail="The pricing manifest does not itself grant authority or expose private payment credentials."/></Pillar><Pillar title="Evidence" proof="Needs proof"><HonestEmpty title="Receipt verification is operator-initiated" route="POST /api/v1/x402/verify" detail="Verification and receipt-proof routes are registered, but no payment or receipt request is sent automatically."/></Pillar><Pillar title="Drift" proof="Needs proof"><HonestEmpty title="No settlement/execution join" route="GET /api/v1/pricing" detail="Balances, receipts, and confirmations are not inferred from a pricing manifest."/></Pillar></SectionShell>}
